# Generated by Django 5.1.7 on 2025-03-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_from_address_homepage_intro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
